### ISSUE TITLE
Use yum::yumconfig for managing yum configuration

### ISSUE THREAD

**Issue by andylytical** [ncsa/puppet-profile_update_os#3]
https://github.com/ncsa/puppet-profile_update_os/blob/1ddf82231503dd7ad829264925a8b05ac1279201/manifests/yum_upgrade.pp#L75-L109

Manipulating config files should be a last resort.

**Comment by andylytical** [comment]
Note also that [puppet-yum](https://github.com/voxpupuli/puppet-yum) expects to manage `installonly_limit` by default.
Suggest the parameter should be removed from this profile and allowed to be set via hiera settings directly for puppet-yum. This cleans up the profile and allows the default setting from puppet-yum to be used, which happens to match the default settings we already want.

**Comment by billglick** [comment]
#7 breaks if using `puppet/yum` `yum::config` to set package excludes with wildcards, so cannot currently use `yum::config` to set the package excludes.
